spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

#  jpa:
#    database-platform: ru.vtb.omni.hibernateorm.helper.domain.custom.PostgreSQL10JsonbDialect
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        jdbc:
#          time_zone: UTC

demo:
  api:
    base-path: http://localhost:8081


