spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update


